name: Release

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-22.04

    env:
      OUTPUT_DIR: ./Build/Output/

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libfuse2 \
          
      - name: Install .NET SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      - name: Download appimagetool
        run: |
          wget -q https://github.com/AppImage/AppImageKit/releases/download/continuous/appimagetool-x86_64.AppImage \
            -O appimagetool
          chmod +x appimagetool
          sudo mv appimagetool /usr/local/bin/appimagetool
          
      - name: Build
        run: make build
        
      - name: Build Appimage
        run: make build-appimage