name: Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version'
        required: true

jobs:
  Build-Windows:
    runs-on: windows-latest
    
    env:
      OUTPUT_DIR: ./Build/Output/
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install .NET SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '10.0.x'
          
      - name: Set version vars
        shell: pwsh
        run: |
          "GIT_VERSION=${{ inputs.version }}" >> $env:GITHUB_ENV
          "GIT_SHA=$($env:GITHUB_SHA.Substring(0, 7))" >> $env:GITHUB_ENV
                
      - name: Windows
        run: make publish-windows
          
      - name: Upload Windows artifact
        uses: actions/upload-artifact@v4
        with:
          name: UnityHub-Windows
          path: |
            ${{ env.OUTPUT_DIR }}/UnityHub_Windows.zip
            ${{ env.OUTPUT_DIR }}/UnityHub.msi
        
          
  Build-Linux:
    runs-on: ubuntu-22.04

    env:
      OUTPUT_DIR: ./Build/Output/

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libfuse2 \
          
      - name: Install .NET SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '10.0.x'
          
      - name: Set version vars
        run: |
          echo "GIT_VERSION=${{ inputs.version }}" >> "$GITHUB_ENV"
          echo "GIT_SHA=${GITHUB_SHA::7}" >> "$GITHUB_ENV"
          
      - name: Download appimagetool
        run: |
            wget -q https://github.com/AppImage/AppImageKit/releases/download/continuous/appimagetool-x86_64.AppImage \
            -O appimagetool
            chmod +x appimagetool
            sudo mv appimagetool /usr/local/bin/appimagetool
        
      - name: Linux Appimage
        run: make publish-appimage
          
      - name: Upload AppImage artifact
        uses: actions/upload-artifact@v4
        with:
          name: UnityHub-AppImage
          path: ${{ env.OUTPUT_DIR }}/UnityHub.appimage
          
  Release:
    needs: [Build-Linux, Build-Windows]
    runs-on: ubuntu-22.04
    permissions:
      contents: write
        
    steps:
      - name: Download AppImage artifact
        uses: actions/download-artifact@v4
        with:
            name: UnityHub-AppImage
            path: ./output
            
      - name: Download Windows artifact
        uses: actions/download-artifact@v4
        with:
            name: UnityHub-Windows
            path: ./output

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
            tag_name: ${{ github.event.inputs.version }}
            name: v${{ github.event.inputs.version }}
            files: |
              ./output/UnityHub.appimage
              ./output/UnityHub_Windows.zip
              ./output/UnityHub.msi